import React from 'react';
import NavBar from './NavBar';
import Footer from '../Footer';

const PrivacyPolicy: React.FC = () => {
  return (
    <>
      <NavBar />
      <div className="bg-white min-h-screen">
        <div className="">
          <div className="w-full bg-green-200 min-h-[50vh] py-8 px-4 sm:px-6 lg:px-8 border-b border-gray-200">
            <div className="max-w-4xl mx-auto">
              <h1 className="text-3xl font-bold text-center mt-20 text-gray-900 mb-2">Privacy & Policy</h1>
              <p className="text-gray-600 text-center">
                Last updated: April 23, 2025
              </p>
            </div>
          </div>

          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="prose prose-lg max-w-none">
              <p className="text-gray-600">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p> <br />
              <p className="text-gray-600 mb-8">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Interpretation and Definitions</h2>
                <h2 className="text-xl font-semibold text-gray-800 mb-2">Interpretation</h2>
                <p className="text-gray-600 mb-4">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions.
                  The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h2 className="text-xl font-semibold text-gray-800 mb-2">Definitions</h2>
                <p className="text-gray-600 mb-2">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc list-inside space-y-2 text-gray-600 ml-4 mb-6">
                  <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><span className="font-medium">Application</span> refers to V11 ORDER LISTING, the software program provided by the Company.</li>
                  <li><span className="font-medium">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to V11TECH, Mayiladurai, Tamilnadu.</li>
                  <li><span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li><span className="font-medium">Country</span> refers to: Tamil Nadu, India</li>
                  <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
                  <li><span className="font-medium">Service</span> refers to the Application or the Website or both.</li>
                  <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><span className="font-medium">Third-party Social Media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                  <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><span className="font-medium">Website</span> refers to V11TECH, accessible from <a href="https://v11tech.com/" className="text-blue-600 hover:underline">https://v11tech.com/</a></li>
                  <li><span className="font-medium">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h3 className="text-lg text-center font-semibold text-gray-800 mb-4">Collecting and Using Your Personal Data</h3> <br />
                <h2 className="text-xl font-semibold text-gray-800 mb-2">Types of Data Collected</h2>

                <h2 className="text-xl font-semibold text-gray-700 mb-2">Personal Data</h2>
                <p className="text-gray-600 mb-2">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.
                  Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside space-y-1 text-gray-600 ml-4 mb-4">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>

                <h2 className="text-xl font-semibold text-gray-700 mb-2">Usage Data</h2>
                <p className="text-gray-600 mb-2">
                  Usage Data is collected automatically when using the Service.
                </p>
                <p className="text-gray-600 mb-2">
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="text-gray-600 mb-2">
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p className="text-gray-600 mb-4">
                  We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>

                <h2 className="text-xl font-semibold text-gray-700 mb-2">Information from Third-Party Social Media Services</h2>
                <p className="text-gray-600 mb-2">
                  The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
                </p>
                <ul className="list-disc list-inside space-y-1 text-gray-600 ml-4 mb-2">
                  <li>Google</li>
                  <li>Facebook</li>
                  <li>Instagram</li>
                  <li>Twitter</li>
                  <li>LinkedIn</li>
                </ul>
                <p className="text-gray-600 mb-4">
                  If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
                </p>
                <p className="text-gray-600 mb-4">
                  You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
                </p>
                <h2 className="text-xl font-semibold text-gray-700 mb-2">Information Collected while Using the Application</h2>
                <p className="text-gray-600 mb-4">While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
                <li>Information regarding your location</li> <br />
                <p className="text-gray-600 mb-4">We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
                <p className="text-gray-600 mb-4">You can enable or disable access to this information at any time, through Your Device settings.</p>
                <h2 className="text-xl font-semibold text-gray-700 mb-2">Tracking Technologies and Cookies</h2>
                <p className="text-gray-600 mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <br /> <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                <br /><p className="text-gray-600 mb-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.</p>
                <p className="text-gray-600 mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <li className="text-xl font-semibold text-gray-700">Necessary / Essential Cookies</li>
                <br /><p>Type: Session Cookies <br />
                  <br />
                  Administered by: Us<br />
                  <br />
                  Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                <br /><li className="text-xl font-semibold text-gray-700">Cookies Policy / Notice Acceptance Cookies</li>
                <br />
                <p>Type: Persistent Cookies<br />
                  <br />
                  Administered by: Us<br />
                  <br />
                  Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p> <br />
                <li className="text-xl font-semibold text-gray-700">Functionality Cookies</li><br />
                <p>Type: Persistent Cookies<br />
                  <br />
                  Administered by: Us<br />
                  <br />
                  Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.<br />

                  For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Use of Your Personal Data</h2>
                <p className="text-gray-600 mb-2">The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc list-inside space-y-2 text-gray-600 ml-4 mb-4">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account: to manage Your registration as a user of the Service.The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                  <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

                  </li>
                  <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                  <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                  <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                </ul>
                <p className="text-gray-600 mb-2">We may share Your personal information in the following situations:</p>
                <ul className="list-disc list-inside space-y-2 text-gray-600 ml-4 mb-4">
                  <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                  <li>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                  <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                  <li>With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                  <li>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
                  <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
                </ul>

              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Retention of Your Personal Data</h2>
                <p className="text-gray-600 mb-2">
                  The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className="text-gray-600 mb-4">
                  The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Transfer of Your Personal Data</h2>
                <p className="text-gray-600 mb-2">
                  Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                </p>
                <p className="text-gray-600 mb-2">
                  Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                </p>
                <p className="text-gray-600 mb-4">
                  The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                </p>
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Delete Your Personal Data</h2>
                <p text-gray-600>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.<br />
                  <br />Our Service may give You the ability to delete certain information about You from within the Service.<br />
                  <br />You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.<br />
                  <br />Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Disclosure of Your Personal Data</h2>
                <h2 className="text-xl font-semibold text-gray-800 mb-2">Business Transactions</h2>
                <p className="text-gray-600 mb-4">
                  If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </p>

                <h2 className="text-xl font-semibold text-gray-800 mb-2">Law enforcement</h2>
                <p className="text-gray-600 mb-4">
                  Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>

                <h2 className="text-xl font-semibold text-gray-800 mb-2">Other legal requirements</h2>
                <p className="text-gray-600 mb-2">
                  The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <ul className="list-disc list-inside space-y-1 text-gray-600 ml-4 mb-4">
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Security of Your Personal Data</h2>
                <p className="text-gray-600 mb-4">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Children's Privacy</h2>
                <p className="text-gray-600 mb-2">
                  Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.
                </p>
                <p className="text-gray-600 mb-4">
                  If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Links to Other Websites</h2>
                <p className="text-gray-600 mb-2">
                  Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                </p>
                <p className="text-gray-600 mb-4">
                  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Changes to this Privacy Policy</h2>
                <p className="text-gray-600 mb-2">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className="text-gray-600 mb-2">
                  We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                </p>
                <p className="text-gray-600 mb-4">
                  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-800 mb-4">Contact Us</h2>
                <p className="text-gray-600 mb-2">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <ul className="list-disc list-inside space-y-1 text-gray-600 ml-4 mb-4">
                  <li>By email: <a href="mailto:support@v1ttech.com" className="text-blue-600 hover:underline">support@v1ttech.com</a></li>
                  <li>By visiting this page on our website: <a href="https://v11tech.com/" className="text-blue-600 hover:underline">https://v11tech.com/</a></li>
                </ul>
              </section>

              <div className="text-center text-gray-500 text-sm">
                <p>Last updated: April 23, 2025</p>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default PrivacyPolicy;